MVC/Controllers/PhoneNumberOperatorCodesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BDA.DAL.EF;
using BDA.Domain;
using Microsoft.AspNetCore.Authorization;

namespace BDA.MVC.Controllers
{
    
    public class PhoneNumberOperatorCodesController : Controller
    {
        private readonly BankDepositsContext _context;

        public PhoneNumberOperatorCodesController(BankDepositsContext context)
        {
            _context = context;
        }

        [Authorize(Roles = EmployeePositionConsts.Admin)]
        // GET: PhoneNumberOperatorCodes
        public async Task<IActionResult> Index()
        {
            var bankDepositsContext = _context.PhoneNumberOperatorsCodes.Include(p => p.PhoneNumberOperator);
            return View(await bankDepositsContext.ToListAsync());
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetPhoneNumberOperatorCodesBy(int phoneNumberOperatorId)
        {
            var phoneNumberOperatorCodes = await _context.PhoneNumberOperatorsCodes.Where(a => a.PhoneNumberOperatorId == phoneNumberOperatorId)
                .Select(a => a.Code).ToListAsync();

            return Json(phoneNumberOperatorCodes);
        }

        [Authorize(Roles = EmployeePositionConsts.Admin)]
        // GET: PhoneNumberOperatorCodes/Create
        public IActionResult Create()
        {
            ViewData["PhoneNumberOperatorId"] = new SelectList(_context.PhoneNumberOperators, "Id", "Operator");
            return View();
        }

        [Authorize(Roles = EmployeePositionConsts.Admin)]
        // POST: PhoneNumberOperatorCodes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PhoneNumberOperatorId,Code")] PhoneNumberOperatorCode phoneNumberOperatorCode)
        {
            if (ModelState.IsValid)
            {
                _context.Add(phoneNumberOperatorCode);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PhoneNumberOperatorId"] = new SelectList(_context.PhoneNumberOperators, "Id", "Operator", phoneNumberOperatorCode.PhoneNumberOperatorId);
            return View(phoneNumberOperatorCode);
        }

        [Authorize(Roles = EmployeePositionConsts.Admin)]
        // GET: PhoneNumberOperatorCodes/Delete/5
        public async Task<IActionResult> Delete(int? phoneNumberOperatorId, int? code)
        {
            if (phoneNumberOperatorId == null || code == null)
            {
                return NotFound();
            }

            var phoneNumberOperatorCode = await _context.PhoneNumberOperatorsCodes
                .Include(p => p.PhoneNumberOperator)
                .FirstOrDefaultAsync(m => m.PhoneNumberOperatorId == phoneNumberOperatorId && m.Code == code);
            if (phoneNumberOperatorCode == null)
            {
                return NotFound();
            }

            return View(phoneNumberOperatorCode);
        }

        [Authorize(Roles = EmployeePositionConsts.Admin)]
        // POST: PhoneNumberOperatorCodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? phoneNumberOperatorId, int? code)
        {
            var phoneNumberOperatorCode = await _context.PhoneNumberOperatorsCodes.FirstOrDefaultAsync(m => m.PhoneNumberOperatorId == phoneNumberOperatorId && m.Code == code);
            _context.PhoneNumberOperatorsCodes.Remove(phoneNumberOperatorCode);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PhoneNumberOperatorCodeExists(int id)
        {
            return _context.PhoneNumberOperatorsCodes.Any(e => e.PhoneNumberOperatorId == id);
        }
    }
}

MVC/Controllers/PhoneNumberOperatorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BDA.DAL.EF;
using BDA.Domain;
using Microsoft.AspNetCore.Authorization;

namespace BDA.MVC.Controllers
{
    [Authorize(Roles = EmployeePositionConsts.Admin)]
    public class PhoneNumberOperatorsController : Controller
    {
        private readonly BankDepositsContext _context;

        public PhoneNumberOperatorsController(BankDepositsContext context)
        {
            _context = context;
        }

        // GET: PhoneNumberOperators
        public async Task<IActionResult> Index()
        {
            return View(await _context.PhoneNumberOperators.ToListAsync());
        }

        // GET: PhoneNumberOperators/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phoneNumberOperator = await _context.PhoneNumberOperators
                .FirstOrDefaultAsync(m => m.Id == id);
            if (phoneNumberOperator == null)
            {
                return NotFound();
            }

            return View(phoneNumberOperator);
        }

        // GET: PhoneNumberOperators/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PhoneNumberOperators/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Operator,Id")] PhoneNumberOperator phoneNumberOperator)
        {
            if (ModelState.IsValid)
            {
                _context.Add(phoneNumberOperator);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(phoneNumberOperator);
        }

        // GET: PhoneNumberOperators/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phoneNumberOperator = await _context.PhoneNumberOperators.FindAsync(id);
            if (phoneNumberOperator == null)
            {
                return NotFound();
            }
            return View(phoneNumberOperator);
        }

        // POST: PhoneNumberOperators/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Operator,Id")] PhoneNumberOperator phoneNumberOperator)
        {
            if (id != phoneNumberOperator.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(phoneNumberOperator);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhoneNumberOperatorExists(phoneNumberOperator.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(phoneNumberOperator);
        }

        // GET: PhoneNumberOperators/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phoneNumberOperator = await _context.PhoneNumberOperators
                .FirstOrDefaultAsync(m => m.Id == id);
            if (phoneNumberOperator == null)
            {
                return NotFound();
            }

            return View(phoneNumberOperator);
        }

        // POST: PhoneNumberOperators/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var phoneNumberOperator = await _context.PhoneNumberOperators.FindAsync(id);
            _context.PhoneNumberOperators.Remove(phoneNumberOperator);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PhoneNumberOperatorExists(int id)
        {
            return _context.PhoneNumberOperators.Any(e => e.Id == id);
        }
    }
}

MVC/Views/PhoneNumberOperators/Create.cshtml
@model BDA.Domain.PhoneNumberOperator

@{
    ViewData["Title"] = "Добавление";
}

<h1>Добавить</h1>

<h4>PhoneNumberOperator</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Operator" class="control-label"></label>
                <input asp-for="Operator" class="form-control" />
                <span asp-validation-for="Operator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Views/PhoneNumberOperators/Delete.cshtml
@model BDA.Domain.PhoneNumberOperator

@{
    ViewData["Title"] = "Удаление";
}

<h1>Удаление</h1>

<h3>Вы уверены, что хотите удалить это?</h3>
<div>
    <h4>Оператор связи</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Operator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Operator)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Вернуться к списку</a>
    </form>
</div>

MVC/Views/PhoneNumberOperators/Details.cshtml
@model BDA.Domain.PhoneNumberOperator

@{
    ViewData["Title"] = "Подробности";
}

<h1>Подробности</h1>

<div>
    <h4>Оператор связи</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Operator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Operator)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Изменить</a> |
    <a asp-action="Index">Вернуться к списку</a>
</div>

MVC/Views/PhoneNumberOperators/Edit.cshtml
@model BDA.Domain.PhoneNumberOperator

@{
    ViewData["Title"] = "Изменение";
}

<h1>Изменение</h1>

<h4>Оператор связи</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Operator" class="control-label"></label>
                <input asp-for="Operator" class="form-control" />
                <span asp-validation-for="Operator" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Views/PhoneNumberOperators/Index.cshtml
@model IEnumerable<BDA.Domain.PhoneNumberOperator>

@{
    ViewData["Title"] = "Список";
}

<h1>Операторы связи</h1>

<p>
    <a asp-action="Create">Добавить</a>
</p>
<p>
    <a asp-action="Index" asp-controller="PhoneNumberOperatorCodes">Прикрепить коды к операторам</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Operator)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Operator)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>