MVC/Controllers/DepositorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BDA.DAL.EF;
using BDA.Domain;
using Microsoft.AspNetCore.Authorization;

namespace BDA.MVC.Controllers
{
    [Authorize]
    public class DepositorsController : Controller
    {
        private readonly BankDepositsContext _context;

        public DepositorsController(BankDepositsContext context)
        {
            _context = context;
        }

        // GET: Depositors
        public async Task<IActionResult> Index()
        {
            var bankDepositsContext = _context.Depositors.Include(d => d.Address).ThenInclude(d => d.Street).ThenInclude(d => d.Locality)
                .Include(d => d.Passport).Include(d => d.PhoneNumber).ThenInclude(d => d.Operator);
            return View(await bankDepositsContext.ToListAsync());
        }

        // GET: Depositors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var depositor = await _context.Depositors
                .Include(d => d.Address).ThenInclude(s => s.Street).ThenInclude(s => s.Locality)
                .Include(d => d.Passport)
                .Include(d => d.PhoneNumber).ThenInclude(s => s.Operator)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (depositor == null)
            {
                return NotFound();
            }

            return View(depositor);
        }

        [Authorize(Roles = EmployeePositionConsts.Manager)]
        // GET: Depositors/Create
        public IActionResult Create()
        {
            ViewBag.Addresses = _context.Addresses.Include(s => s.Street).Select(s => new SelectListItem($"{s.Street.Locality.LocalityName} {s.Street.StreetName} {s.House} {s.Housing}", s.Id.ToString()));
            ViewBag.Passports = _context.Passports.Select(s => new SelectListItem(s.FullName, s.Id.ToString()));
            ViewBag.PhoneNumbers = _context.PhoneNumbers.Include(s => s.Operator).Select(s => new SelectListItem($"{s.Operator.Operator} {s.OperatorCode} {s.Number}", s.Id.ToString()));
            return View();
        }

        [Authorize(Roles = EmployeePositionConsts.Manager)]
        // POST: Depositors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PassportId,AddressId,PhoneNumberId,Email,Id")] Depositor depositor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(depositor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Addresses = _context.Addresses.Include(s => s.Street).Select(s => new SelectListItem($"{s.Street.Locality.LocalityName} {s.Street.StreetName} {s.House} {s.Housing}", s.Id.ToString()));
            ViewBag.Passports = _context.Passports.Select(s => new SelectListItem(s.FullName, s.Id.ToString()));
            ViewBag.PhoneNumbers = _context.PhoneNumbers.Include(s => s.Operator).Select(s => new SelectListItem($"{s.Operator.Operator} {s.OperatorCode} {s.Number}", s.Id.ToString()));
            return View(depositor);
        }

        [Authorize(Roles = EmployeePositionConsts.Manager)]
        // GET: Depositors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var depositor = await _context.Depositors.FindAsync(id);
            if (depositor == null)
            {
                return NotFound();
            }
            ViewBag.Addresses = _context.Addresses.Include(s => s.Street).Select(s => new SelectListItem($"{s.Street.Locality.LocalityName} {s.Street.StreetName} {s.House} {s.Housing}", s.Id.ToString()));
            ViewBag.Passports = _context.Passports.Select(s => new SelectListItem(s.FullName, s.Id.ToString()));
            ViewBag.PhoneNumbers = _context.PhoneNumbers.Include(s => s.Operator).Select(s => new SelectListItem($"{s.Operator.Operator} {s.OperatorCode} {s.Number}", s.Id.ToString()));
            return View(depositor);
        }

        [Authorize(Roles = EmployeePositionConsts.Manager)]
        // POST: Depositors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PassportId,AddressId,PhoneNumberId,Email,Id")] Depositor depositor)
        {
            if (id != depositor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(depositor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepositorExists(depositor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Addresses = _context.Addresses.Include(s => s.Street).Select(s => new SelectListItem($"{s.Street.Locality.LocalityName} {s.Street.StreetName} {s.House} {s.Housing}", s.Id.ToString()));
            ViewBag.Passports = _context.Passports.Select(s => new SelectListItem(s.FullName, s.Id.ToString()));
            ViewBag.PhoneNumbers = _context.PhoneNumbers.Include(s => s.Operator).Select(s => new SelectListItem($"{s.Operator.Operator} {s.OperatorCode} {s.Number}", s.Id.ToString()));
            return View(depositor);
        }

        // GET: Depositors/Delete/5
        [Authorize(Roles = EmployeePositionConsts.Manager)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var depositor = await _context.Depositors
                .Include(d => d.Address)
                .Include(d => d.Passport)
                .Include(d => d.PhoneNumber)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (depositor == null)
            {
                return NotFound();
            }

            return View(depositor);
        }

        // POST: Depositors/Delete/5
        [Authorize(Roles = EmployeePositionConsts.Manager)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var depositor = await _context.Depositors.FindAsync(id);
            _context.Depositors.Remove(depositor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepositorExists(int id)
        {
            return _context.Depositors.Any(e => e.Id == id);
        }
    }
}

MVC/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BDA.DAL.EF;
using BDA.Domain;
using Microsoft.AspNetCore.Authorization;

namespace BDA.MVC.Controllers
{
    [Authorize]
    public class EmployeesController : Controller
    {
        private readonly BankDepositsContext _context;

        public EmployeesController(BankDepositsContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            var bankDepositsContext = _context.Employees.Include(e => e.Address).Include(e => e.Passport).Include(e => e.PhoneNumber);
            return View(await bankDepositsContext.ToListAsync());
        }
        
        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Address)
                .Include(e => e.Passport)
                .Include(e => e.PhoneNumber)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        [Authorize(Roles = EmployeePositionConsts.Admin)]
        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Address)
                .Include(e => e.Passport)
                .Include(e => e.PhoneNumber)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        [Authorize(Roles = EmployeePositionConsts.Admin)]
        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _context.Employees.FindAsync(id);
            _context.Employees.Remove(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.Id == id);
        }
    }
}

MVC/Controllers/PhoneNumberOperatorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BDA.DAL.EF;
using BDA.Domain;
using Microsoft.AspNetCore.Authorization;

namespace BDA.MVC.Controllers
{
    [Authorize(Roles = EmployeePositionConsts.Admin)]
    public class PhoneNumberOperatorsController : Controller
    {
        private readonly BankDepositsContext _context;

        public PhoneNumberOperatorsController(BankDepositsContext context)
        {
            _context = context;
        }

        // GET: PhoneNumberOperators
        public async Task<IActionResult> Index()
        {
            return View(await _context.PhoneNumberOperators.ToListAsync());
        }

        // GET: PhoneNumberOperators/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phoneNumberOperator = await _context.PhoneNumberOperators
                .FirstOrDefaultAsync(m => m.Id == id);
            if (phoneNumberOperator == null)
            {
                return NotFound();
            }

            return View(phoneNumberOperator);
        }

        // GET: PhoneNumberOperators/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PhoneNumberOperators/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Operator,Id")] PhoneNumberOperator phoneNumberOperator)
        {
            if (ModelState.IsValid)
            {
                _context.Add(phoneNumberOperator);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(phoneNumberOperator);
        }

        // GET: PhoneNumberOperators/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phoneNumberOperator = await _context.PhoneNumberOperators.FindAsync(id);
            if (phoneNumberOperator == null)
            {
                return NotFound();
            }
            return View(phoneNumberOperator);
        }

        // POST: PhoneNumberOperators/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Operator,Id")] PhoneNumberOperator phoneNumberOperator)
        {
            if (id != phoneNumberOperator.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(phoneNumberOperator);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhoneNumberOperatorExists(phoneNumberOperator.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(phoneNumberOperator);
        }

        // GET: PhoneNumberOperators/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var phoneNumberOperator = await _context.PhoneNumberOperators
                .FirstOrDefaultAsync(m => m.Id == id);
            if (phoneNumberOperator == null)
            {
                return NotFound();
            }

            return View(phoneNumberOperator);
        }

        // POST: PhoneNumberOperators/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var phoneNumberOperator = await _context.PhoneNumberOperators.FindAsync(id);
            _context.PhoneNumberOperators.Remove(phoneNumberOperator);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PhoneNumberOperatorExists(int id)
        {
            return _context.PhoneNumberOperators.Any(e => e.Id == id);
        }
    }
}

MVC/Views/PhoneNumbers/Create.cshtml
@model BDA.Domain.PhoneNumber

@{
    ViewData["Title"] = "Добавление";
}

<h1>Добавить</h1>

<h4>Телефонный номер</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OperatorId" class="control-label"></label>
                <select asp-for="OperatorId" class ="form-control" asp-items="ViewBag.OperatorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="OperatorCode" class="control-label"></label>
                <input asp-for="OperatorCode" class="form-control" />
                <span asp-validation-for="OperatorCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Views/PhoneNumbers/Delete.cshtml
@model BDA.Domain.PhoneNumber

@{
    ViewData["Title"] = "Удаление";
}

<h1>Удаление</h1>

<h3>Вы уверены, что хотите удалить это?</h3>
<div>
    <h4>Телефонный номер</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OperatorCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OperatorCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Operator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Operator.Operator)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Вернуться к списку</a>
    </form>
</div>

MVC/Views/PhoneNumbers/Edit.cshtml
@model BDA.Domain.PhoneNumber

@{
    ViewData["Title"] = "Изменение";
}

<h1>Изменение</h1>

<h4>Телефонный номер</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OperatorId" class="control-label"></label>
                <select asp-for="OperatorId" class="form-control" asp-items="ViewBag.OperatorId"></select>
                <span asp-validation-for="OperatorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OperatorCode" class="control-label"></label>
                <input asp-for="OperatorCode" class="form-control" />
                <span asp-validation-for="OperatorCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Views/PhoneNumbers/Index.cshtml
@model IEnumerable<BDA.Domain.PhoneNumber>

@{
    ViewData["Title"] = "Список";
}

<h1>Телефонные номера</h1>

<p>
    <a asp-action="Create">Добавить</a>
</p>
<p>
    <a asp-action="Index" asp-controller="PhoneNumberOperators">Операторы связи</a>
</p>
<p>
    <a asp-action="Index" asp-controller="Depositors">Клиенты</a>
</p>
<p>
    <a asp-action="Create" asp-controller="Employees">Сотрудники</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OperatorCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Operator)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OperatorCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Operator.Operator)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>