MVC/Controllers/AddressesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BDA.DAL.EF;
using BDA.Domain;
using Microsoft.AspNetCore.Authorization;

namespace BDA.MVC.Controllers
{
    [Authorize(Roles = EmployeePositionConsts.Manager)]
    public class AddressesController : Controller
    {
        private readonly BankDepositsContext _context;

        public AddressesController(BankDepositsContext context)
        {
            _context = context;
        }

        // GET: Addresses
        public async Task<IActionResult> Index()
        {
            var bankDepositsContext = _context.Addresses.Include(a => a.Street);
            return View(await bankDepositsContext.ToListAsync());
        }

        // GET: Addresses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Addresses
                .Include(a => a.Street)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // GET: Addresses/Create
        public IActionResult Create()
        {
            ViewData["StreetId"] = new SelectList(_context.Streets, "Id", "StreetName");
            return View();
        }

        // POST: Addresses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StreetId,House,Housing,Apartment,Id")] Address address)
        {
            if (ModelState.IsValid)
            {
                _context.Add(address);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StreetId"] = new SelectList(_context.Streets, "Id", "StreetName", address.StreetId);
            return View(address);
        }

        // GET: Addresses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Addresses.FindAsync(id);
            if (address == null)
            {
                return NotFound();
            }
            ViewData["StreetId"] = new SelectList(_context.Streets, "Id", "StreetName", address.StreetId);
            return View(address);
        }

        // POST: Addresses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StreetId,House,Housing,Apartment,Id")] Address address)
        {
            if (id != address.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(address);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AddressExists(address.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StreetId"] = new SelectList(_context.Streets, "Id", "StreetName", address.StreetId);
            return View(address);
        }

        // GET: Addresses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Addresses
                .Include(a => a.Street)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // POST: Addresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var address = await _context.Addresses.FindAsync(id);
            _context.Addresses.Remove(address);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AddressExists(int id)
        {
            return _context.Addresses.Any(e => e.Id == id);
        }
    }
}

MVC/Controllers/PassportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BDA.DAL.EF;
using BDA.Domain;
using Microsoft.AspNetCore.Authorization;
using BDA.Core;

namespace BDA.MVC.Controllers
{
    [Authorize(Roles = EmployeePositionConsts.Manager)]
    public class PassportsController : Controller
    {
        private readonly IEmployeeRepository employeeRepository;
        private readonly IIssuingAuthorityRepository issuingAuthorityRepository;
        private readonly ILocalityRepository localityRepository;
        private readonly IPhoneNumberOperatorRepository phoneNumberOperatorRepository;
        private readonly IIssuingAuthorityLocalityRepository issuingAuthorityLocalityRepository;
        private readonly IStreetRepository streetRepository;
        private readonly BankDepositsContext _context;

        public PassportsController(BankDepositsContext context,
            IEmployeeRepository employeeRepository,
            IIssuingAuthorityRepository issuingAuthorityRepository,
            ILocalityRepository localityRepository,
            IPhoneNumberOperatorRepository phoneNumberOperatorRepository,
            IIssuingAuthorityLocalityRepository issuingAuthorityLocalityRepository,
            IStreetRepository streetRepository)
        {
            _context = context;
            this.employeeRepository = employeeRepository;
            this.issuingAuthorityRepository = issuingAuthorityRepository;
            this.localityRepository = localityRepository;
            this.phoneNumberOperatorRepository = phoneNumberOperatorRepository;
            this.issuingAuthorityLocalityRepository = issuingAuthorityLocalityRepository;
            this.streetRepository = streetRepository;
        }

        // GET: Passports
        public async Task<IActionResult> Index()
        {
            var bankDepositsContext = _context.Passports.Include(p => p.IssuingAuthorityLocality);
            return View(await bankDepositsContext.ToListAsync());
        }

        // GET: Passports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passport = await _context.Passports
                .Include(p => p.IssuingAuthorityLocality)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (passport == null)
            {
                return NotFound();
            }

            return View(passport);
        }

        // GET: Passports/Create
        public async Task<IActionResult> Create()
        {
            var localities = await localityRepository.GetBy().ToListAsync();
            ViewBag.Localities = localities.Select(a => new SelectListItem($"{a.Region} {a.LocalityName}", a.Id.ToString()));

            var firstLocality = localities.FirstOrDefault();

            if (firstLocality != null)
            {
                var issuingAuthorityLocalities = await issuingAuthorityLocalityRepository.GetBy(a => a.LocalityId == firstLocality.Id, a => a.IssuingAuthority).ToListAsync();
                ViewBag.IssuingAuthorities = issuingAuthorityLocalities
                    .Select(a => new SelectListItem(a.IssuingAuthority.Name, a.IssuingAuthority.Id.ToString()));
            }

            ViewBag.Citizenships = CitizenshipConsts.Dict.Select(c => new SelectListItem(c.Value, c.Key.ToString()));
            return View();
        }

        // POST: Passports/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,MiddleName,LastName,BirthDate,Gender,CitizenshipId,Number,IdentificationNumber,IssuingAuthorityId,IssuingAuthorityLocalityId,IssueDate,ExpirationDate,Citizenship,Id")] Passport passport)
        {
            if (ModelState.IsValid)
            {
                _context.Add(passport);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            var localities = await localityRepository.GetBy().ToListAsync();
            ViewBag.Localities = localities.Select(a => new SelectListItem($"{a.Region} {a.LocalityName}", a.Id.ToString()));

            var firstLocality = localities.FirstOrDefault();

            if (firstLocality != null)
            {
                var issuingAuthorityLocalities = await issuingAuthorityLocalityRepository.GetBy(a => a.LocalityId == firstLocality.Id, a => a.IssuingAuthority).ToListAsync();
                ViewBag.IssuingAuthorities = issuingAuthorityLocalities
                    .Select(a => new SelectListItem(a.IssuingAuthority.Name, a.IssuingAuthority.Id.ToString()));
            }

            ViewBag.Citizenships = CitizenshipConsts.Dict.Select(c => new SelectListItem(c.Value, c.Key.ToString()));

            return View(passport);
        }

        // GET: Passports/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passport = await _context.Passports.FindAsync(id);
            if (passport == null)
            {
                return NotFound();
            }

            var localities = await localityRepository.GetBy().ToListAsync();
            ViewBag.Localities = localities.Select(a => new SelectListItem($"{a.Region} {a.LocalityName}", a.Id.ToString()));

            var firstLocality = localities.FirstOrDefault();

            if (firstLocality != null)
            {
                var issuingAuthorityLocalities = await issuingAuthorityLocalityRepository.GetBy(a => a.LocalityId == firstLocality.Id, a => a.IssuingAuthority).ToListAsync();
                ViewBag.IssuingAuthorities = issuingAuthorityLocalities
                    .Select(a => new SelectListItem(a.IssuingAuthority.Name, a.IssuingAuthority.Id.ToString()));
            }

            ViewBag.Citizenships = CitizenshipConsts.Dict.Select(c => new SelectListItem(c.Value, c.Key.ToString()));

            return View(passport);
        }

        // POST: Passports/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,MiddleName,LastName,BirthDate,Gender,CitizenshipId,Number,IdentificationNumber,IssuingAuthorityId,IssuingAuthorityLocalityId,IssueDate,ExpirationDate,Citizenship,Id")] Passport passport)
        {
            if (id != passport.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(passport);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PassportExists(passport.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            var localities = await localityRepository.GetBy().ToListAsync();
            ViewBag.Localities = localities.Select(a => new SelectListItem($"{a.Region} {a.LocalityName}", a.Id.ToString()));

            var firstLocality = localities.FirstOrDefault();

            if (firstLocality != null)
            {
                var issuingAuthorityLocalities = await issuingAuthorityLocalityRepository.GetBy(a => a.LocalityId == firstLocality.Id, a => a.IssuingAuthority).ToListAsync();
                ViewBag.IssuingAuthorities = issuingAuthorityLocalities
                    .Select(a => new SelectListItem(a.IssuingAuthority.Name, a.IssuingAuthority.Id.ToString()));
            }

            ViewBag.Citizenships = CitizenshipConsts.Dict.Select(c => new SelectListItem(c.Value, c.Key.ToString()));

            return View(passport);
        }

        // GET: Passports/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var passport = await _context.Passports
                .Include(p => p.IssuingAuthorityLocality)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (passport == null)
            {
                return NotFound();
            }

            return View(passport);
        }

        // POST: Passports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var passport = await _context.Passports.FindAsync(id);
            _context.Passports.Remove(passport);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PassportExists(int id)
        {
            return _context.Passports.Any(e => e.Id == id);
        }
    }
}

MVC/Views/Depositors/Create.cshtml
@model BDA.Domain.Depositor

@{
    ViewData["Title"] = "Create";
}

<h1>Добавить</h1>

<h4>Клиент</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PassportId" class="control-label"></label>
                <select asp-for="PassportId" class ="form-control" asp-items="(IEnumerable<SelectListItem>)ViewBag.Passports"></select>
            </div>
            <div class="form-group">
                <label asp-for="AddressId" class="control-label"></label>
                <select asp-for="AddressId" class ="form-control" asp-items="(IEnumerable<SelectListItem>)ViewBag.Addresses"></select>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumberId" class="control-label"></label>
                <select asp-for="PhoneNumberId" class ="form-control" asp-items="(IEnumerable<SelectListItem>)ViewBag.PhoneNumbers"></select>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Views/Depositors/Delete.cshtml
@model BDA.Domain.Depositor

@{
    ViewData["Title"] = "Удаление";
}

<h1>Удаление</h1>

<h3>Вы уверены, что хотите удалить это?</h3>
<div>
    <h4>Клиент</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Passport)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Passport.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber.Id)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Вернуться к списку</a>
    </form>
</div>

MVC/Views/Depositors/Details.cshtml
@using BDA.Domain;
@model BDA.Domain.Depositor

@{
    ViewData["Title"] = "Подробности";
}

<h1>Подробности</h1>

<div>
    <h4>Клиент</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address.Street.Locality.LocalityName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.Street.Locality.LocalityName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address.Street.StreetName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.Street.StreetName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address.Street.Postcode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.Street.Postcode)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address.House)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.House)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address.Housing)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.Housing)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address.Apartment)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address.Apartment)
        </dd>


        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Passport)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Passport.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Passport.MiddleName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Passport.MiddleName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Passport.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Passport.LastName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Passport.BirthDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Passport.BirthDate)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber.Id)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber.Operator)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber.Operator.Operator)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber.OperatorCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber.OperatorCode)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber.Number)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber.Number)
        </dd>
    </dl>
</div>
<div>
    @if (User.IsInRole(EmployeePosition.Manager.ToString()))
    {
    <p>
        <a asp-action="Edit" asp-route-id="@Model.Id">Изменить</a>
    </p>
    }
    <a asp-action="Index">Вернуться к списку</a>
</div>

MVC/Views/Depositors/Edit.cshtml
@model BDA.Domain.Depositor

@{
    ViewData["Title"] = "Изменение";
}

<h1>Изменить</h1>

<h4>Клиент</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PassportId" class="control-label"></label>
                <select asp-for="PassportId" class="form-control" asp-items="(IEnumerable<SelectListItem>)ViewBag.Passports"></select>
                <span asp-validation-for="PassportId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddressId" class="control-label"></label>
                <select asp-for="AddressId" class="form-control" asp-items="(IEnumerable<SelectListItem>)ViewBag.Addresses"></select>
                <span asp-validation-for="AddressId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumberId" class="control-label"></label>
                <select asp-for="PhoneNumberId" class="form-control" asp-items="(IEnumerable<SelectListItem>)ViewBag.PhoneNumbers"></select>
                <span asp-validation-for="PhoneNumberId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Views/Depositors/Index.cshtml
@using BDA.Domain;
@model IEnumerable<BDA.Domain.Depositor>

@{
    ViewData["Title"] = "Список";
}

<h1>Клиенты</h1>

@if (User.IsInRole(EmployeePosition.Manager.ToString()))
{
    <p>
        <a asp-action="Create">Добавить</a>
    </p>
    <p>
        <a asp-action="Index" asp-controller="Addresses">Адреса</a>
    </p>
    <p>
        <a asp-action="Index" asp-controller="Passports">Паспорта</a>
    </p>
    <p>
        <a asp-action="Index" asp-controller="PhoneNumbers">Телефонные номера</a>
    </p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address.Street.Locality.LocalityName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address.Street.StreetName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Passport.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber.Operator.Operator)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber.OperatorCode)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber.Number)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address.Street.Locality.LocalityName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address.Street.StreetName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Passport.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber.Operator.Operator)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber.OperatorCode)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber.Number)
                </td>
                <td>
                    @if (User.IsInRole(EmployeePosition.Manager.ToString()))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Изменить</a>
                        <a asp-action="Details" asp-route-id="@item.Id">Подробнее</a>
                        <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
                    }
                    else
                    {

                        <a asp-action="Details" asp-route-id="@item.Id">Подробнее</a>

                    }
                </td>
            </tr>
        }
    </tbody>
</table>