MVC/Controllers/IssuingAuthorityLocalitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BDA.DAL.EF;
using BDA.Domain;
using Microsoft.AspNetCore.Authorization;

namespace BDA.MVC.Controllers
{
    
    public class IssuingAuthorityLocalitiesController : Controller
    {
        private readonly BankDepositsContext _context;

        public IssuingAuthorityLocalitiesController(BankDepositsContext context)
        {
            _context = context;
        }

        // GET: IssuingAuthorityLocalities
        public async Task<IActionResult> Index()
        {
            var bankDepositsContext = _context.IssuingAuthoritiesLocalities.Include(i => i.IssuingAuthority).Include(i => i.Locality);
            return View(await bankDepositsContext.ToListAsync());
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetIssuingAuthoritesBy(int? localityId)
        {
            if (localityId == null)
            {
                return NotFound();
            }

            var issuingAuthorities = await _context.IssuingAuthoritiesLocalities
                .Where(m => m.LocalityId == localityId)
                .Select(m => m.IssuingAuthority).ToListAsync();

            return Json(issuingAuthorities);
        }

        [Authorize(Roles = EmployeePositionConsts.Admin)]
        // GET: IssuingAuthorityLocalities/Create
        public IActionResult Create()
        {
            ViewData["IssuingAuthorityId"] = new SelectList(_context.IssuingAuthorities, "Id", "Name");
            ViewData["LocalityId"] = new SelectList(_context.Localities, "Id", "LocalityName");
            return View();
        }

        [Authorize(Roles = EmployeePositionConsts.Admin)]
        // POST: IssuingAuthorityLocalities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IssuingAuthorityId,LocalityId")] IssuingAuthorityLocality issuingAuthorityLocality)
        {
            if (ModelState.IsValid)
            {
                _context.Add(issuingAuthorityLocality);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IssuingAuthorityId"] = new SelectList(_context.IssuingAuthorities, "Id", "Name", issuingAuthorityLocality.IssuingAuthorityId);
            ViewData["LocalityId"] = new SelectList(_context.Localities, "Id", "LocalityName", issuingAuthorityLocality.LocalityId);
            return View(issuingAuthorityLocality);
        }

        [Authorize(Roles = EmployeePositionConsts.Admin)]
        // GET: IssuingAuthorityLocalities/Delete/5
        public async Task<IActionResult> Delete(int? issuingAuthorityId, int? localityId)
        {
            if (issuingAuthorityId == null || localityId == null)
            {
                return NotFound();
            }

            var issuingAuthorityLocality = await _context.IssuingAuthoritiesLocalities
                .Include(i => i.IssuingAuthority)
                .Include(i => i.Locality)
                .FirstOrDefaultAsync(m => m.IssuingAuthorityId == issuingAuthorityId && m.LocalityId == localityId);
            if (issuingAuthorityLocality == null)
            {
                return NotFound();
            }

            return View(issuingAuthorityLocality);
        }

        [Authorize(Roles = EmployeePositionConsts.Admin)]
        // POST: IssuingAuthorityLocalities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? issuingAuthorityId, int? localityId)
        {
            var issuingAuthorityLocality = await _context.IssuingAuthoritiesLocalities.FirstOrDefaultAsync(m => m.IssuingAuthorityId == issuingAuthorityId && m.LocalityId == localityId);
            _context.IssuingAuthoritiesLocalities.Remove(issuingAuthorityLocality);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IssuingAuthorityLocalityExists(int id)
        {
            return _context.IssuingAuthoritiesLocalities.Any(e => e.IssuingAuthorityId == id);
        }
    }
}

MVC/Controllers/LocalitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BDA.DAL.EF;
using BDA.Domain;
using Microsoft.AspNetCore.Authorization;

namespace BDA.MVC.Controllers
{
    [Authorize(Roles = EmployeePositionConsts.Admin)]
    public class LocalitiesController : Controller
    {
        private readonly BankDepositsContext _context;

        public LocalitiesController(BankDepositsContext context)
        {
            _context = context;
        }

        // GET: Localities
        public async Task<IActionResult> Index()
        {
            return View(await _context.Localities.ToListAsync());
        }

        // GET: Localities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var locality = await _context.Localities
                .FirstOrDefaultAsync(m => m.Id == id);
            if (locality == null)
            {
                return NotFound();
            }

            return View(locality);
        }

        // GET: Localities/Create
        public IActionResult Create()
        {
            ViewBag.LocalityTypes = LocalityTypeConsts.Dict.Select(a => new SelectListItem(a.Value, a.Key.ToString()));

            return View();
        }

        // POST: Localities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Region,LocalityName,LocalityType,Id")] Locality locality)
        {
            if (ModelState.IsValid)
            {
                locality.Region = locality.Region ?? "";
                _context.Add(locality);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(locality);
        }

        // GET: Localities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var locality = await _context.Localities.FindAsync(id);
            if (locality == null)
            {
                return NotFound();
            }

            ViewBag.LocalityTypes = LocalityTypeConsts.Dict.Select(a => new SelectListItem(a.Value, a.Key.ToString()));

            return View(locality);
        }

        // POST: Localities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Region,LocalityName,LocalityType,Id")] Locality locality)
        {
            if (id != locality.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(locality);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocalityExists(locality.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(locality);
        }

        // GET: Localities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var locality = await _context.Localities
                .FirstOrDefaultAsync(m => m.Id == id);
            if (locality == null)
            {
                return NotFound();
            }

            return View(locality);
        }

        // POST: Localities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var locality = await _context.Localities.FindAsync(id);
            _context.Localities.Remove(locality);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LocalityExists(int id)
        {
            return _context.Localities.Any(e => e.Id == id);
        }
    }
}

MVC/Controllers/StreetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BDA.DAL.EF;
using BDA.Domain;
using Microsoft.AspNetCore.Authorization;

namespace BDA.MVC.Controllers
{
    
    public class StreetsController : Controller
    {
        private readonly BankDepositsContext _context;

        public StreetsController(BankDepositsContext context)
        {
            _context = context;
        }

        [Authorize(Roles = EmployeePositionConsts.Manager)]
        // GET: Streets
        public async Task<IActionResult> Index()
        {
            var bankDepositsContext = _context.Streets.Include(s => s.Locality);
            return View(await bankDepositsContext.ToListAsync());
        }

        [Authorize(Roles = EmployeePositionConsts.Manager)]
        // GET: Streets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var street = await _context.Streets
                .Include(s => s.Locality)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (street == null)
            {
                return NotFound();
            }

            return View(street);
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetStreetsBy(int localityId)
        {
            var streets = await _context.Streets.Where(a => a.LocalityId == localityId).ToListAsync();

            return Json(streets);
        }

        [Authorize(Roles = EmployeePositionConsts.Manager)]
        // GET: Streets/Create
        public IActionResult Create()
        {
            ViewData["LocalityId"] = new SelectList(_context.Localities, "Id", "LocalityName");
            return View();
        }

        [Authorize(Roles = EmployeePositionConsts.Manager)]
        // POST: Streets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LocalityId,StreetName,Postcode,Id")] Street street)
        {
            if (ModelState.IsValid)
            {
                _context.Add(street);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocalityId"] = new SelectList(_context.Localities, "Id", "LocalityName", street.LocalityId);
            return View(street);
        }

        [Authorize(Roles = EmployeePositionConsts.Manager)]
        // GET: Streets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var street = await _context.Streets.FindAsync(id);
            if (street == null)
            {
                return NotFound();
            }
            ViewData["LocalityId"] = new SelectList(_context.Localities, "Id", "LocalityName", street.LocalityId);
            return View(street);
        }

        [Authorize(Roles = EmployeePositionConsts.Manager)]
        // POST: Streets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LocalityId,StreetName,Postcode,Id")] Street street)
        {
            if (id != street.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(street);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StreetExists(street.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocalityId"] = new SelectList(_context.Localities, "Id", "LocalityName", street.LocalityId);
            return View(street);
        }

        [Authorize(Roles = EmployeePositionConsts.Manager)]
        // GET: Streets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var street = await _context.Streets
                .Include(s => s.Locality)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (street == null)
            {
                return NotFound();
            }

            return View(street);
        }

        [Authorize(Roles = EmployeePositionConsts.Manager)]
        // POST: Streets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var street = await _context.Streets.FindAsync(id);
            _context.Streets.Remove(street);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StreetExists(int id)
        {
            return _context.Streets.Any(e => e.Id == id);
        }
    }
}

MVC/Views/Localities/Create.cshtml
@model BDA.Domain.Locality

@{
    ViewData["Title"] = "Добавление";
}

<h1>Добавить</h1>

<h4>Населённый пункт</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocalityName" class="control-label"></label>
                <input asp-for="LocalityName" class="form-control" />
                <span asp-validation-for="LocalityName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocalityType" class="control-label"></label>
                <select asp-for="LocalityType" class="form-control" asp-items="(IEnumerable<SelectListItem>)ViewBag.LocalityTypes"></select>
                <span asp-validation-for="LocalityType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Views/Localities/Delete.cshtml
@model BDA.Domain.Locality

@{
    ViewData["Title"] = "Удаление";
}

<h1>Удаление</h1>

<h3>Вы уверены, что хотите удалить это?</h3>
<div>
    <h4>Населённый пункт</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocalityName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocalityName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocalityType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocalityType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Вернуться к списку</a>
    </form>
</div>

MVC/Views/Localities/Details.cshtml
@model BDA.Domain.Locality

@{
    ViewData["Title"] = "Подробности";
}

<h1>Подробности</h1>

<div>
    <h4>Населённый пункт</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocalityName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocalityName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocalityType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocalityType)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Изменить</a> |
    <a asp-action="Index">Вернуться к списку</a>
</div>

MVC/Views/Localities/Edit.cshtml
@model BDA.Domain.Locality

@{
    ViewData["Title"] = "Изменение";
}

<h1>Изменение</h1>

<h4>Населённый пункт</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocalityName" class="control-label"></label>
                <input asp-for="LocalityName" class="form-control" />
                <span asp-validation-for="LocalityName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocalityType" class="control-label"></label>
                <select asp-for="LocalityType" class="form-control" asp-items="(IEnumerable<SelectListItem>)ViewBag.LocalityTypes"></select>
                <span asp-validation-for="LocalityType" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC/Views/Localities/Index.cshtml
@model IEnumerable<BDA.Domain.Locality>

@{
    ViewData["Title"] = "Список";
}

<h1>Населённые пункт</h1>

<p>
    <a asp-action="Create">Добавить</a>
</p>
<p>
    <a asp-action="Index" asp-controller="IssuingAuthorityLocalities">Прикрепить выдающие органы к населённым пунктам</a>
</p>
<p>
    <a asp-action="Index" asp-controller="Streets">Прикрепить улицы к населённым пунктам</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Region)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LocalityName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LocalityTypeName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Region)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocalityName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocalityType)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>